### ISSUE TITLE
Select still using Less mixins

### ISSUE THREAD

**Issue by dialpad-drew** [dialpad/dialtone#305]
Select's sizes are still using Less mixins from `variables/sizes.less`.

```less
//  $$  SIZES
  //  ----------------------------------------------------------------------------
  &--xs {
    font-size: var(--fs14);
    .d-select__input {
      .input-button-xs();
    }
  }
  &--sm {
    font-size: var(--fs16);
    .d-select__input {
      .input-button-sm();
    }
  }
  &--lg {
    font-size: var(--fs20);
    .d-select__input {
      .input-button-lg();
    }
  }
  &--xl {
    font-size: var(--fs24);
    .d-select__input {
      .input-button-xl();
    }
  }
}
```

We should move these to Less or CSS vars.
